'use server'

import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { Resend } from 'resend'

// ─── Create ───────────────────────────────────────────────────────────────────

/**
 * Creates a new household and makes the caller its first admin.
 * The invite_code is generated automatically by the DB trigger.
 */
export async function createHousehold(formData: FormData) {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated.' }

  const name = (formData.get('name') as string).trim()
  if (!name || name.length < 2) return { error: 'Household name must be at least 2 characters.' }
  if (name.length > 80)         return { error: 'Household name must be 80 characters or fewer.' }

  // Create the household (invite_code auto-generated by trigger)
  const { data: household, error: hErr } = await supabase
    .from('households')
    .insert({ name, created_by: user.id })
    .select('id, name, invite_code')
    .single()

  if (hErr || !household) return { error: hErr?.message ?? 'Could not create household.' }

  // Add current user as admin
  const { error: mErr } = await supabase
    .from('household_members')
    .insert({ user_id: user.id, household_id: household.id, role: 'admin' })

  if (mErr) {
    // Roll back the orphaned household
    await supabase.from('households').delete().eq('id', household.id)
    return { error: mErr.message }
  }

  revalidatePath('/', 'layout')
  return { success: true, household }
}

// ─── Join ─────────────────────────────────────────────────────────────────────

/**
 * Looks up a household by invite code and adds the caller as a member.
 * Normalises the code to uppercase so casing doesn't matter.
 */
export async function joinHousehold(formData: FormData) {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated.' }

  const rawCode = (formData.get('code') as string ?? '').trim().toUpperCase()
  if (rawCode.length !== 6) return { error: 'Invite codes are exactly 6 characters.' }

  // Find the household
  const { data: household, error: hErr } = await supabase
    .from('households')
    .select('id, name')
    .eq('invite_code', rawCode)
    .maybeSingle()

  if (hErr || !household) {
    return { error: 'No household found with that code. Double-check and try again.' }
  }

  // Join as member
  const { error: mErr } = await supabase
    .from('household_members')
    .insert({ user_id: user.id, household_id: household.id, role: 'member' })

  if (mErr) return { error: mErr.message }

  revalidatePath('/', 'layout')
  return { success: true, household }
}

// ─── Rename ───────────────────────────────────────────────────────────────────

export async function updateHouseholdName(formData: FormData) {
  const supabase = await createClient()

  const householdId = formData.get('householdId') as string
  const name        = (formData.get('name') as string).trim()

  if (!name || name.length < 2) return { error: 'Name must be at least 2 characters.' }
  if (name.length > 80)         return { error: 'Name must be 80 characters or fewer.' }

  const { data: isAdmin } = await supabase.rpc('is_household_admin', {
    p_household_id: householdId,
  })
  if (!isAdmin) return { error: 'Only admins can rename the household.' }

  const { error } = await supabase
    .from('households')
    .update({ name })
    .eq('id', householdId)

  if (error) return { error: error.message }

  revalidatePath('/household')
  return { success: true }
}

// ─── Regenerate invite code ───────────────────────────────────────────────────

export async function regenerateInviteCode(householdId: string) {
  const supabase = await createClient()

  const { data: isAdmin } = await supabase.rpc('is_household_admin', {
    p_household_id: householdId,
  })
  if (!isAdmin) return { error: 'Only admins can regenerate the invite code.' }

  // Retry up to 8 times to find a unique code
  for (let attempt = 0; attempt < 8; attempt++) {
    const { data: code, error: genErr } = await supabase.rpc('generate_invite_code')
    if (genErr || !code) continue

    const { data: collision } = await supabase
      .from('households')
      .select('id')
      .eq('invite_code', code)
      .neq('id', householdId) // ignore our own current code
      .maybeSingle()

    if (collision) continue // try again

    const { error: updateErr } = await supabase
      .from('households')
      .update({ invite_code: code })
      .eq('id', householdId)

    if (updateErr) return { error: updateErr.message }

    revalidatePath('/household')
    return { success: true, code }
  }

  return { error: 'Could not generate a unique code. Please try again.' }
}

// ─── Send invite email ────────────────────────────────────────────────────────

/**
 * Send an email invitation to join the household.
 * Uses Resend (RESEND_API_KEY env var). Works for any household member —
 * not admin-only, since any member can invite someone they know.
 */
export async function sendInviteEmail(householdId: string, recipientEmail: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated.' }

  // Validate email format
  const emailRe = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  if (!emailRe.test(recipientEmail.trim())) {
    return { error: 'Please enter a valid email address.' }
  }

  // Verify sender is a member of this household
  const { data: membership } = await supabase
    .from('household_members')
    .select('user_id')
    .eq('user_id', user.id)
    .eq('household_id', householdId)
    .maybeSingle()

  if (!membership) return { error: 'You are not a member of this household.' }

  // Fetch household name + invite code
  const { data: household } = await supabase
    .from('households')
    .select('name, invite_code')
    .eq('id', householdId)
    .maybeSingle()

  if (!household) return { error: 'Household not found.' }

  // Fetch sender's display name
  const { data: senderProfile } = await supabase
    .from('users')
    .select('full_name, email')
    .eq('id', user.id)
    .maybeSingle()

  const senderName = (senderProfile as { full_name: string | null; email: string } | null)
    ?.full_name ?? user.email ?? 'Your housemate'

  const siteUrl   = (process.env.NEXT_PUBLIC_SITE_URL ?? '').replace(/\/$/, '')
  const joinUrl   = `${siteUrl}/join/${household.invite_code}`
  const apiKey    = process.env.RESEND_API_KEY

  if (!apiKey) return { error: 'Email service not configured. Share your invite link manually.' }

  const resend = new Resend(apiKey)

  const { error: sendError } = await resend.emails.send({
    from:    'ChoreSync <help@choresync.com>',
    to:      [recipientEmail.trim()],
    subject: `${senderName} invited you to join ${household.name} on ChoreSync`,
    html:    buildInviteEmail({
      senderName,
      householdName: household.name,
      inviteCode:    household.invite_code,
      joinUrl,
    }),
  })

  if (sendError) {
    console.error('Resend error:', sendError)
    return { error: 'Failed to send the invite email. Please try again.' }
  }

  return { success: true }
}

// ── Email template ────────────────────────────────────────────────────────────

function buildInviteEmail({
  senderName,
  householdName,
  inviteCode,
  joinUrl,
}: {
  senderName:    string
  householdName: string
  inviteCode:    string
  joinUrl:       string
}): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>You're invited to join ${householdName}</title>
</head>
<body style="margin:0;padding:0;background:#F7F8FA;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F7F8FA;padding:40px 0;">
    <tr>
      <td align="center">
        <table width="480" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:20px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">

          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#FF6B2B,#FF8C5A);padding:36px 40px 28px;text-align:center;">
              <div style="font-size:36px;margin-bottom:8px;">🏠</div>
              <p style="margin:0;font-size:22px;font-weight:800;color:#ffffff;letter-spacing:-0.3px;">
                You're invited!
              </p>
              <p style="margin:8px 0 0;font-size:14px;color:rgba(255,255,255,0.85);">
                Join <strong>${householdName}</strong> on ChoreSync
              </p>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:32px 40px;">
              <p style="margin:0 0 16px;font-size:15px;color:#374151;line-height:1.6;">
                Hey there! <strong>${senderName}</strong> has invited you to join their household
                <strong>${householdName}</strong> on ChoreSync — the app that makes sharing chores
                fair and stress-free.
              </p>

              <!-- Invite code pill -->
              <table width="100%" cellpadding="0" cellspacing="0" style="margin:24px 0;">
                <tr>
                  <td style="background:#FFF3EE;border:2px dashed #FFB899;border-radius:14px;padding:20px;text-align:center;">
                    <p style="margin:0 0 6px;font-size:12px;font-weight:700;color:#FF6B2B;text-transform:uppercase;letter-spacing:0.08em;">
                      Your invite code
                    </p>
                    <p style="margin:0;font-size:32px;font-weight:800;color:#FF6B2B;letter-spacing:0.15em;">
                      ${inviteCode}
                    </p>
                  </td>
                </tr>
              </table>

              <!-- CTA button -->
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td align="center" style="padding:4px 0 24px;">
                    <a href="${joinUrl}"
                       style="display:inline-block;background:#FF6B2B;color:#ffffff;text-decoration:none;
                              font-size:16px;font-weight:700;padding:14px 40px;border-radius:12px;
                              box-shadow:0 4px 14px rgba(255,107,43,0.35);">
                      Accept Invitation →
                    </a>
                  </td>
                </tr>
              </table>

              <p style="margin:0;font-size:13px;color:#9CA3AF;line-height:1.6;">
                Or open ChoreSync and enter the code above manually. The link and code never expire —
                share it whenever you're ready.
              </p>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background:#F9FAFB;border-top:1px solid #F0F0F0;padding:20px 40px;text-align:center;">
              <p style="margin:0;font-size:12px;color:#9CA3AF;">
                Sent by ChoreSync on behalf of ${senderName}.
                If you weren't expecting this, you can safely ignore it.
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`
}

// ─── Member role ──────────────────────────────────────────────────────────────

/**
 * Admin-only: promote a member to admin or demote an admin to member.
 * Guards against demoting the last admin.
 */
export async function updateMemberRole(
  memberId:    string,
  householdId: string,
  newRole:     'admin' | 'member'
) {
  const supabase = await createClient()

  const { data: isAdmin } = await supabase.rpc('is_household_admin', {
    p_household_id: householdId,
  })
  if (!isAdmin) return { error: 'Only admins can change member roles.' }

  if (newRole === 'member') {
    // Ensure at least one admin will remain
    const { count } = await supabase
      .from('household_members')
      .select('*', { count: 'exact', head: true })
      .eq('household_id', householdId)
      .eq('role', 'admin')

    if ((count ?? 0) <= 1) {
      return { error: 'Cannot demote the last admin. Promote another member first.' }
    }
  }

  const { error } = await supabase
    .from('household_members')
    .update({ role: newRole })
    .eq('id', memberId)

  if (error) return { error: error.message }

  revalidatePath('/household')
  return { success: true }
}

// ─── Remove member ────────────────────────────────────────────────────────────

/**
 * Admin-only: remove any other member from the household.
 * An admin cannot remove themselves via this action — use leaveHousehold instead.
 */
export async function removeMember(memberId: string, householdId: string) {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated.' }

  const { data: isAdmin } = await supabase.rpc('is_household_admin', {
    p_household_id: householdId,
  })
  if (!isAdmin) return { error: 'Only admins can remove members.' }

  // Fetch the target membership
  const { data: target } = await supabase
    .from('household_members')
    .select('user_id, role')
    .eq('id', memberId)
    .eq('household_id', householdId)
    .maybeSingle()

  if (!target) return { error: 'Member not found in this household.' }
  if (target.user_id === user.id) return { error: 'Use "Leave Household" to remove yourself.' }

  if (target.role === 'admin') {
    const { count } = await supabase
      .from('household_members')
      .select('*', { count: 'exact', head: true })
      .eq('household_id', householdId)
      .eq('role', 'admin')

    if ((count ?? 0) <= 1) {
      return { error: 'Cannot remove the last admin. Promote another member first.' }
    }
  }

  const { error } = await supabase
    .from('household_members')
    .delete()
    .eq('id', memberId)

  if (error) return { error: error.message }

  revalidatePath('/household')
  return { success: true }
}

// ─── Leave ────────────────────────────────────────────────────────────────────

/**
 * Lets the current user exit a household.
 * If they are the last admin and other members exist, they must promote
 * someone before leaving.
 */
export async function leaveHousehold(householdId: string) {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated.' }

  // Fetch caller's membership
  const { data: membership } = await supabase
    .from('household_members')
    .select('id, role')
    .eq('user_id', user.id)
    .eq('household_id', householdId)
    .maybeSingle()

  if (!membership) return { error: 'You are not a member of this household.' }

  if (membership.role === 'admin') {
    const { count: adminCount } = await supabase
      .from('household_members')
      .select('*', { count: 'exact', head: true })
      .eq('household_id', householdId)
      .eq('role', 'admin')

    const { count: totalCount } = await supabase
      .from('household_members')
      .select('*', { count: 'exact', head: true })
      .eq('household_id', householdId)

    const isLastAdmin = (adminCount ?? 0) <= 1
    const hasOthers   = (totalCount ?? 0) > 1

    if (isLastAdmin && hasOthers) {
      return {
        error:
          'You are the only admin. Promote another member to admin before leaving.',
      }
    }
  }

  const { error } = await supabase
    .from('household_members')
    .delete()
    .eq('id', membership.id)

  if (error) return { error: error.message }

  revalidatePath('/', 'layout')
  redirect('/onboarding')
}

// ─── Update member colour ─────────────────────────────────────────────────────

/** Any member can update their own display colour within the household. */
export async function updateMemberColor(householdId: string, color: string) {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated.' }

  const { error } = await supabase
    .from('household_members')
    .update({ color_theme: color })
    .eq('user_id', user.id)
    .eq('household_id', householdId)

  if (error) return { error: error.message }

  revalidatePath('/household')
  return { success: true }
}

// ─── Kids mode ────────────────────────────────────────────────────────────────

export async function setMemberKidsMode(memberId: string, householdId: string, enable: boolean) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated.' }

  const { data: isAdmin } = await supabase.rpc('is_household_admin', { p_household_id: householdId })
  if (!isAdmin) return { error: 'Only admins can change roles.' }

  const { data: target } = await supabase
    .from('household_members')
    .select('user_id, role')
    .eq('id', memberId)
    .eq('household_id', householdId)
    .maybeSingle()

  if (!target) return { error: 'Member not found.' }
  if (target.user_id === user.id) return { error: 'You cannot put yourself in kids mode.' }
  if (target.role === 'admin') return { error: 'Demote this admin to member first.' }

  const { error } = await supabase
    .from('household_members')
    .update({ role: enable ? 'kids' : 'member' })
    .eq('id', memberId)

  if (error) return { error: error.message }
  revalidatePath('/household')
  return { success: true }
}

// ─── Join via shareable link ──────────────────────────────────────────────────

export async function joinViaLink(code: string, displayName: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Please sign in first to join a household.' }

  const upperCode = code.trim().toUpperCase()

  const { data: household } = await supabase
    .from('households')
    .select('id, name')
    .eq('invite_code', upperCode)
    .maybeSingle()

  if (!household) return { error: 'Invalid or expired invite link.' }

  const { data: alreadyIn } = await supabase
    .from('household_members')
    .select('id')
    .eq('user_id', user.id)
    .eq('household_id', household.id)
    .maybeSingle()

  if (alreadyIn) return { error: 'You are already a member of this household.' }

  if (displayName.trim()) {
    const { error: nameErr } = await supabase
      .from('users')
      .update({ full_name: displayName.trim() })
      .eq('id', user.id)
    if (nameErr) return { error: 'Could not save your display name. Please try again.' }
  }

  const { error: joinErr } = await supabase
    .from('household_members')
    .insert({ user_id: user.id, household_id: household.id, role: 'member' })

  if (joinErr) return { error: joinErr.message }

  revalidatePath('/', 'layout')
  return { success: true, householdName: household.name }
}
