'use server'

import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

// ─── Create ───────────────────────────────────────────────────────────────────

/**
 * Creates a new household and makes the caller its first admin.
 * The invite_code is generated automatically by the DB trigger.
 */
export async function createHousehold(formData: FormData) {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated.' }

  const name = (formData.get('name') as string).trim()
  if (!name || name.length < 2) return { error: 'Household name must be at least 2 characters.' }
  if (name.length > 80)         return { error: 'Household name must be 80 characters or fewer.' }

  // Check the user isn't already in a household
  const { data: existing } = await supabase
    .from('household_members')
    .select('household_id')
    .eq('user_id', user.id)
    .maybeSingle()

  if (existing) return { error: 'You are already in a household. Leave it first.' }

  // Create the household (invite_code auto-generated by trigger)
  const { data: household, error: hErr } = await supabase
    .from('households')
    .insert({ name, created_by: user.id })
    .select('id, name, invite_code')
    .single()

  if (hErr || !household) return { error: hErr?.message ?? 'Could not create household.' }

  // Add current user as admin
  const { error: mErr } = await supabase
    .from('household_members')
    .insert({ user_id: user.id, household_id: household.id, role: 'admin' })

  if (mErr) {
    // Roll back the orphaned household
    await supabase.from('households').delete().eq('id', household.id)
    return { error: mErr.message }
  }

  revalidatePath('/', 'layout')
  return { success: true, household }
}

// ─── Join ─────────────────────────────────────────────────────────────────────

/**
 * Looks up a household by invite code and adds the caller as a member.
 * Normalises the code to uppercase so casing doesn't matter.
 */
export async function joinHousehold(formData: FormData) {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated.' }

  const rawCode = (formData.get('code') as string ?? '').trim().toUpperCase()
  if (rawCode.length !== 6) return { error: 'Invite codes are exactly 6 characters.' }

  // Check the user isn't already in a household
  const { data: existing } = await supabase
    .from('household_members')
    .select('household_id')
    .eq('user_id', user.id)
    .maybeSingle()

  if (existing) return { error: 'You are already in a household. Leave it first.' }

  // Find the household
  const { data: household, error: hErr } = await supabase
    .from('households')
    .select('id, name')
    .eq('invite_code', rawCode)
    .maybeSingle()

  if (hErr || !household) {
    return { error: 'No household found with that code. Double-check and try again.' }
  }

  // Join as member
  const { error: mErr } = await supabase
    .from('household_members')
    .insert({ user_id: user.id, household_id: household.id, role: 'member' })

  if (mErr) return { error: mErr.message }

  revalidatePath('/', 'layout')
  return { success: true, household }
}

// ─── Rename ───────────────────────────────────────────────────────────────────

export async function updateHouseholdName(formData: FormData) {
  const supabase = await createClient()

  const householdId = formData.get('householdId') as string
  const name        = (formData.get('name') as string).trim()

  if (!name || name.length < 2) return { error: 'Name must be at least 2 characters.' }
  if (name.length > 80)         return { error: 'Name must be 80 characters or fewer.' }

  const { data: isAdmin } = await supabase.rpc('is_household_admin', {
    p_household_id: householdId,
  })
  if (!isAdmin) return { error: 'Only admins can rename the household.' }

  const { error } = await supabase
    .from('households')
    .update({ name })
    .eq('id', householdId)

  if (error) return { error: error.message }

  revalidatePath('/household')
  return { success: true }
}

// ─── Regenerate invite code ───────────────────────────────────────────────────

export async function regenerateInviteCode(householdId: string) {
  const supabase = await createClient()

  const { data: isAdmin } = await supabase.rpc('is_household_admin', {
    p_household_id: householdId,
  })
  if (!isAdmin) return { error: 'Only admins can regenerate the invite code.' }

  // Retry up to 8 times to find a unique code
  for (let attempt = 0; attempt < 8; attempt++) {
    const { data: code, error: genErr } = await supabase.rpc('generate_invite_code')
    if (genErr || !code) continue

    const { data: collision } = await supabase
      .from('households')
      .select('id')
      .eq('invite_code', code)
      .neq('id', householdId) // ignore our own current code
      .maybeSingle()

    if (collision) continue // try again

    const { error: updateErr } = await supabase
      .from('households')
      .update({ invite_code: code })
      .eq('id', householdId)

    if (updateErr) return { error: updateErr.message }

    revalidatePath('/household')
    return { success: true, code }
  }

  return { error: 'Could not generate a unique code. Please try again.' }
}

// ─── Member role ──────────────────────────────────────────────────────────────

/**
 * Admin-only: promote a member to admin or demote an admin to member.
 * Guards against demoting the last admin.
 */
export async function updateMemberRole(
  memberId:    string,
  householdId: string,
  newRole:     'admin' | 'member'
) {
  const supabase = await createClient()

  const { data: isAdmin } = await supabase.rpc('is_household_admin', {
    p_household_id: householdId,
  })
  if (!isAdmin) return { error: 'Only admins can change member roles.' }

  if (newRole === 'member') {
    // Ensure at least one admin will remain
    const { count } = await supabase
      .from('household_members')
      .select('*', { count: 'exact', head: true })
      .eq('household_id', householdId)
      .eq('role', 'admin')

    if ((count ?? 0) <= 1) {
      return { error: 'Cannot demote the last admin. Promote another member first.' }
    }
  }

  const { error } = await supabase
    .from('household_members')
    .update({ role: newRole })
    .eq('id', memberId)

  if (error) return { error: error.message }

  revalidatePath('/household')
  return { success: true }
}

// ─── Remove member ────────────────────────────────────────────────────────────

/**
 * Admin-only: remove any other member from the household.
 * An admin cannot remove themselves via this action — use leaveHousehold instead.
 */
export async function removeMember(memberId: string, householdId: string) {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated.' }

  const { data: isAdmin } = await supabase.rpc('is_household_admin', {
    p_household_id: householdId,
  })
  if (!isAdmin) return { error: 'Only admins can remove members.' }

  // Fetch the target membership
  const { data: target } = await supabase
    .from('household_members')
    .select('user_id, role')
    .eq('id', memberId)
    .eq('household_id', householdId)
    .maybeSingle()

  if (!target) return { error: 'Member not found in this household.' }
  if (target.user_id === user.id) return { error: 'Use "Leave Household" to remove yourself.' }

  if (target.role === 'admin') {
    const { count } = await supabase
      .from('household_members')
      .select('*', { count: 'exact', head: true })
      .eq('household_id', householdId)
      .eq('role', 'admin')

    if ((count ?? 0) <= 1) {
      return { error: 'Cannot remove the last admin. Promote another member first.' }
    }
  }

  const { error } = await supabase
    .from('household_members')
    .delete()
    .eq('id', memberId)

  if (error) return { error: error.message }

  revalidatePath('/household')
  return { success: true }
}

// ─── Leave ────────────────────────────────────────────────────────────────────

/**
 * Lets the current user exit a household.
 * If they are the last admin and other members exist, they must promote
 * someone before leaving.
 */
export async function leaveHousehold(householdId: string) {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated.' }

  // Fetch caller's membership
  const { data: membership } = await supabase
    .from('household_members')
    .select('id, role')
    .eq('user_id', user.id)
    .eq('household_id', householdId)
    .maybeSingle()

  if (!membership) return { error: 'You are not a member of this household.' }

  if (membership.role === 'admin') {
    const { count: adminCount } = await supabase
      .from('household_members')
      .select('*', { count: 'exact', head: true })
      .eq('household_id', householdId)
      .eq('role', 'admin')

    const { count: totalCount } = await supabase
      .from('household_members')
      .select('*', { count: 'exact', head: true })
      .eq('household_id', householdId)

    const isLastAdmin = (adminCount ?? 0) <= 1
    const hasOthers   = (totalCount ?? 0) > 1

    if (isLastAdmin && hasOthers) {
      return {
        error:
          'You are the only admin. Promote another member to admin before leaving.',
      }
    }
  }

  const { error } = await supabase
    .from('household_members')
    .delete()
    .eq('id', membership.id)

  if (error) return { error: error.message }

  revalidatePath('/', 'layout')
  redirect('/onboarding')
}

// ─── Update member colour ─────────────────────────────────────────────────────

/** Any member can update their own display colour within the household. */
export async function updateMemberColor(householdId: string, color: string) {
  const supabase = await createClient()

  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated.' }

  const { error } = await supabase
    .from('household_members')
    .update({ color_theme: color })
    .eq('user_id', user.id)
    .eq('household_id', householdId)

  if (error) return { error: error.message }

  revalidatePath('/household')
  return { success: true }
}
